services:
  - type: web
    name: freshfarm-web-platform
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
      - key: DATABASE_URL
        value: postgresql://freshfarm:yMOjDnD1YW604685saPQOFX1A6Tj5pCL@dpg-dah9ugeq1p3s73b86ndg-a.singapore-postgres.render.com/freshfarm_db_7pjf?sslmode=require
